ALTER TABLE `Organization`
  ADD COLUMN `playgroundEnabled` BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE `AiRequest`
  MODIFY COLUMN `task` ENUM(
    'GENERATE_QUESTIONS',
    'GRADE_ANSWER',
    'GRADE_CODE',
    'EXPLAIN_ANSWER',
    'PLAYGROUND_ADVICE',
    'GENERATE_REMEDIAL',
    'GENERATE_REPORT'
  ) NOT NULL;
