ALTER TABLE `Assignment`
  ADD COLUMN `type` ENUM('GENERAL', 'CODE') NOT NULL DEFAULT 'GENERAL',
  ADD COLUMN `codeLanguage` ENUM('C', 'CPP', 'CSHARP', 'PYTHON') NULL,
  ADD COLUMN `aiGradingEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `aiGradingModel` VARCHAR(191) NULL;

ALTER TABLE `AiRequest`
  MODIFY COLUMN `task` ENUM('GENERATE_QUESTIONS', 'GRADE_ANSWER', 'GRADE_CODE', 'EXPLAIN_ANSWER', 'GENERATE_REMEDIAL', 'GENERATE_REPORT') NOT NULL;
